services:
  frontend:
    build: ./consiliario-front
    ports:
      - 8000:80

  backend:
    build: ./server
    ports:
      - 8080:8080

  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
