spring:
  main:
    web-application-type: reactive
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    schema: consiliario
    username: postgres
    password: admin
    pool:
      initial-size: 100
      max-size: 500
      max-idle-time: 30m
      validation-query: SELECT

  flyway:
    validate-migration-naming: true
    url: jdbc:postgresql://localhost:5432/postgres
    locations: classpath:db/migration

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

  datasource:
    initialization-mode: always
    initialize: true
    schema: classpath:/schema.sql
    continue-on-error: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 35MB

jwt:
  secret: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-01234567890123456789012345678
  expiration: 28800