spring:
  main:
    web-application-type: reactive
  r2dbc:
    url: r2dbc:postgresql://database:5432/postgres
    schema: consiliario
    username: postgres
    password: admin
    pool:
      initial-size: 100
      max-size: 500
      max-idle-time: 30m
      validation-query: SELECT

  flyway:
    validate-migration-naming: true
    url: jdbc:postgresql://database:5432/postgres
    locations: classpath:db/migration

  web:
    resources:
      add-mappings: false

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 35MB
  sql:
    init:
      mode: always
      continue-on-error: true

jwt:
  secret: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-01234567890123456789012345678
  expiration: 28800